// src/lib/components/Footer/Footer.svelte
<script>
	import { Footer, FooterCopyright, FooterLinkGroup, FooterLink } from 'flowbite-svelte';

	const currentYear = new Date().getFullYear();
</script>

<Footer class="bg-white dark:bg-gray-900">
	<div class="container mx-auto px-6">
		<hr class="dark:bg-grey-900 border-gray-200 dark:border-gray-700 sm:mx-auto lg:my-8" />
		<div class="sm:flex sm:items-center sm:justify-between">
			<FooterCopyright
				href="/"
				by="Alexander Swensen"
				year={currentYear}
				class="text-gray-800 dark:text-white"
			/>
			<FooterLinkGroup
				ulClass="flex flex-wrap items-center mt-3 text-sm text-gray-600 dark:text-gray-300 sm:mt-0"
			>
				<FooterLink href="/about">About</FooterLink>
				<FooterLink href="https://github.com/AlexSwensen" target="_blank">Github</FooterLink>
			</FooterLinkGroup>
		</div>
	</div>
</Footer>

// src/components/Footer.tsx
export function Footer() {
  return (
    <footer className="bg-muted text-muted-foreground py-8 mt-16">
      <div className="container mx-auto px-4 text-center">
        <p className="text-sm sm:text-base">
          © {new Date().getFullYear()} Alexander Swensen. All rights reserved.
        </p>
        <div className="mt-4 flex flex-col sm:flex-row justify-center space-y-2 sm:space-y-0 sm:space-x-4">
          <a
            href="https://github.com/AlexSwensen"
            target="_blank"
            rel="noopener noreferrer"
            className="hover:text-primary transition-colors"
          >
            GitHub
          </a>
          <a
            href="https://www.linkedin.com/in/alexswensen/"
            target="_blank"
            rel="noopener noreferrer"
            className="hover:text-primary transition-colors"
          >
            LinkedIn
          </a>
          <a
            href="https://x.com/alexswensen_"
            target="_blank"
            rel="noopener noreferrer"
            className="hover:text-primary transition-colors"
          >
            Twitter
          </a>
        </div>
      </div>
    </footer>
  );
}
